### ISSUE TITLE
Issue: Requirement to submit Metadata before creation of DOI

### ISSUE THREAD

**Issue by timgiles** [inveniosoftware/datacite#27]
Hi,

I have created an extension for CKAN to create DOIs with Datacite, using this library. My metadata validates AOK, but when I try to create a DOI, I get a message stating that I need to submit metadata first before creating the DOI (only with Test).

How can I do that?

If I manually upload the metadata via Datacites website, I am able to update the metadata using the library.

**Comment by lnielsen** [comment]
I think it's probably just because you have to call ``metadata_post()`` before ``doi_post()``, similar to this:

```
# Initialize the MDS client.
d = DataCiteMDSClient(...)

# Submit metadata
d.metadata_post(doc)

# Register DOI
d.doi_post('10.5072/test-doi', 'http://example.org/test-doi')
```

**Comment by timgiles** [comment]
Hi,

I am running the commands in that order. If I print the output of : 

returnvar = d.metadata_post(doc)
print returnvar

I get : OK (10.5072/60757383884) (only test mode!)

The next two lines are: 

returnvar2 = d.doi_post(doi.identifier, get_site_url() + '/dataset/' + package_id)
print returnvar2

which crashes on the returnvar2= .....

WebError Traceback:
⇝ DataCitePreconditionError: You have to register metadata first! (only test mode!)
View as:   Interactive (full)  |  Text (full)  |  XML (full)
Module ckanext.slugui.slupackage:248 in pubsub_update          view
>>  self.submit(context, id)
Module ckanext.slugui.slupackage:385 in submit          view
>>  updated_dict = get_action('package_patch')(context, data_dict)
Module ckan.logic:416 in wrapped          view
>>  result = _action(context, data_dict, **kw)
Module ckan.logic.action.patch:41 in package_patch          view
>>  return _update.package_update(context, patched)
Module ckan.logic.action.update:370 in package_update          view
>>  item.after_update(context, data)
Module ckanext.doi.plugin:465 in after_update          view
>>  returnvar2 = d.doi_post(doi.identifier, get_site_url() + '/dataset/' + package_id)
Module datacite.client:103 in doi_post          view
>>  raise DataCiteError.factory(r.code, r.data)
DataCitePreconditionError: You have to register metadata first! (only test mode!)

Also, if I log in to https://mds.datacite.org/ I can see in the test datasets that no DOI has been created.


Any ideas?

Regards Timothy

**Comment by lnielsen** [comment]
Sorry, didn't catch in the first place that you were in test mode. DataCite MDS in test mode doesn't store anything, so when you run ``d.metadata_post(doc)`` then the document is actually not saved by DataCite MDS, hence it's not available when you then run ``d.doi_post(...)``.

In order to properly test the DOI registration you have to use the ``10.5072`` prefix and switch off test mode. It's actually a bit misleading to call it test mode - "dry run" would probably be appropriate term. 

See https://mds.datacite.org/static/apidoc#tocAnchor-9
