### ISSUE TITLE
Generate new DOI

### ISSUE THREAD

**Issue by nichtich** [inveniosoftware/datacite#29]
I miss a method to generate a new DOI as described at https://support.datacite.org/docs/mds-2#section-generating-a-doi-name How about porting the method from Cirneco to Python?

**Comment by lnielsen** [comment]
Makes sense. Not sure when we will get around to it however.

**Comment by nichtich** [comment]
Cirneco generates "a random number that is Base32 Crockford encoded and includes a checksum". I ported and extended the function to Python:

~~~python
import base32_crockford
import random

def generate_doi(prefix, split=4, blocks=2):
    """
    Generate a random DOI in the format `prefix/xxxx-xxxx`.

    The DOI suffix will consist of digits and lowercase characters
    (Crockford's base32) providing 5 bit randomness each.

    Args:
       prefix (string): DOI prefix
       split (integer): number of characters per block (default: 4)
       blocks (integer): number of blocks to separate by hyphen (default: 2)

    Returns:
        string: generated DOI with random suffix
    """

    number = random.randrange(32**(split*blocks))

    # without checksum because it could include ugly characters (*, ~, $)
    suffix = base32_crockford.encode(number, split=split).lower()

    return '%s/%s' % (prefix, suffix)
~~~

Example:

    > generate_doi('10.5072', split=5)
    10.5072/nhs3h-mfgzp

**Comment by tmorrell** [comment]
If we want to be completely consistent with DataCite, we'd need to include a mod 97-10, ISO 7064 checksum as implemented in https://github.com/datacite/base32-url.  Although, I think with the new API you can let the DataCite server generate the DOI with the recommended formatting, so this might not be crucial.

**Comment by tmorrell** [comment]
In the new REST interface, if you don't provide a DOI DataCite will automatically create one for you with the recommended format. For example:

'''
import os
from datacite import DataCiteRESTClient

username = os.environ["DATACITE_USER"]
password = os.environ["DATACITE_PW"]
prefix = os.environ["DATACITE_PREFIX"]

client = DataCiteRESTClient(
        username=username,
        password=password,
        prefix=prefix,
        test_mode=True,
    )

doi = client.draft_doi()
print(doi)
'''

Returns a recommended style DOI like `10.33569/amb8-3b36`. This works for all the DOI creation operations in the REST interface.
