### ISSUE TITLE
Add support for DataCite v4.1

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/datacite#31]

**Comment by krzysztof** [comment]
Some questions/comments regarding the [4.1 Schema documentation](https://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf)

1. In the website and PDF changelog we can find: ``Addition of new “dateInformation” subproperty for dateType``, but from the schema it looks like it's a subproperty of "date". I'm assuming it's a mistake in changelog, so I'm adding it as a subproperty of "date".
1. ``Addition of a new optional “nameType” attribute for Creator and Contributor. Controlled list: personal, organizational``: It looks like it's a subproperty of Creator/Contributor, except the field ID under Creator (page 13) stays: ``ID: 2.1.1``, suggesting it's a subfield of ``2.1 Creator Name``. For contributor it's clear it's a subfield of "contributor", hence I'm assuming that this is also a mistake in the docs in case of the "Creator"
1. ``Addition of optional lang attribute to Rights property``. Lang is actually not added to the documentation, I'm adding it as a string field, subproperty of "rights"

Relevant changes: https://github.com/inveniosoftware/datacite/pull/33/commits/cc39a2ae470b46bd2a098f9f56b521cad4c65b68#diff-0f2071ab975760c84ff83ddbf6e45044

**Comment by krzysztof** [comment]
- [ ] Allowing multiple polygons per GeoLocation
- [ ] Addition of new optional “inPolygonPoint” subproperties for polygon
- [ ] Addition of new dateType “Other”
- [ ] Addition of new “dateInformation” subproperty for dateType
- [ ] Addition of a new resourceType “DataPaper”
- [ ] Addition of three new relationType pairs: IsDescribedBy and Describes, HasVersion and IsVersionOf, IsRequiredBy and Requires
- [ ] Addition of a new optional “nameType” attribute for Creator and Contributor. Controlled list: personal, organizational
- [ ] Addition of a new optional “resourceTypeGeneral” attribute for relatedIdentifier. Controlled list is identical to existing resourceTypeGeneral attribute
- [ ] Addition of optional lang attribute to Rights property
