### ISSUE TITLE
DataCite Metadata v5.0 update list

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/datacite#35]
Several backwards-compatibility solutions and implementation details that should be dropped with DataCite metadata 5.0:

1. Drop support for single ``geoLocationPolygon`` - schema users should generate ``geoLocationPolygons`` instead.
1. Drop support for ``type`` in the title, users should use ``titleType``.
1. ``nameType`` should be a sub-property of creatorName/contributorName, instead of a direct sub-property of Creator/Contributor. This was kept this way to avoid changing the type of the creatorName/contributor name fiels from string to object between 4.0 -> 4.1 schema updates. In 5.0 ``nameType`` should be a subproperty of creatorName and contributorName, which by themselves should be objects like:
```
   "creatorName": {
     "type": "object",
     "properties": {"creatorName": {"type": "string"}, "nameType": {"enum":[..]}}
   }
```
4. DataCite requires four ``polygonPoint`` elements per ``geoLocationPolygon`` (and ``polygonPoint[0] == polygonPoint[-1]``). So far JSON schema was requiring only 3 and was kept this way for ``geoLocationPolygon`` due to backwards compatibility, with a generation of a missing polygon when necessary (actually the auto-generation was not done until 4.1 upgrade, so it's not clear what the original intention was). The ``geoLocationPolygons`` also requires minimum 3 points. In new kernel, a decision needs to be made whether:
   1. 4 is the new minimum number of points, and the schema validation should fail if first point does not match the last point (or auto-generate)
   1. 3 remains to be the minimum number of points, and we continue to auto generate the last point.

**Comment by tmorrell** [comment]
I'm going to close this issue because it's not clear when DataCite will release 5.0 or what it will contain. We've integrated titleType, and the status for geoLocationPolygon is uncertain from the DataCite side https://github.com/inveniosoftware/datacite/issues/93.
