### ISSUE TITLE
Change url from MDS to Fabrica new endpoint

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/datacite#43]
The previous API url https://mds.datacite.org/ (https://doi.datacite.org/) will be removed. The new one should be: https://doi.datacite.org/.

See:
* https://blog.datacite.org/register-dois-with-the-new-fabrica-form/
* https://blog.datacite.org/fabrica-1-release/

**Comment by tmorrell** [comment]
This is a major API change and will require more than just swapping out the URL.  I'm planning on wrapping the new API with new functions, but I don't have a specific schedule.

**Comment by tmorrell** [comment]
The new REST API has now been merged in and is available for use. The MDS interface is still available as DataCite had not depreciated it yet.
