### ISSUE TITLE
Schema 4.1 mistakes in enums

### ISSUE THREAD

**Issue by phixgre** [inveniosoftware/datacite#44]
Hello,
your JSON translation of Datacite XSD Schema 4.1 is not fully correct! 

There is a mistake with the enum 'nameType' 
https://github.com/inveniosoftware/datacite/blob/master/datacite/schemas/datacite-v4.1.json
http://schema.datacite.org/meta/kernel-4.1/include/datacite-nameType-v4.1.xsd

The good value is 'Organizational' (with a 'z', and not with a 's')

Please check all other enums...

**Comment by tmorrell** [comment]
This has been fixed in the 4.2 and 4.3 schemas. Unless there is a compelling reason, we'll leave the 4.1 schema as is to not break compatibility.
