### ISSUE TITLE
Remove default DataCite test prefix 10.5072 

### ISSUE THREAD

**Issue by miltalex** [inveniosoftware/datacite#46]
Default Datacite test prefix 10.5072 retiring June 1st, 2019. 

Datacite re-introduced a completely separate test system and did away with testing within the production account.

More info:

- https://blog.datacite.org/making-testing-simpler/
- https://blog.datacite.org/test-prefix-10-5072-retiring-june-1/

**Comment by lnielsen** [comment]
Note, see workaround in https://github.com/inveniosoftware/datacite/issues/47#issuecomment-503945132

**Comment by lnielsen** [comment]
Depends on merge of #48 and #45 

Task:
- Remove ``test_mode``, ``api_ver`` and default value (10.5072) for ``prefix`` in [DataCiteMDSClient](https://github.com/inveniosoftware/datacite/blob/master/datacite/client.py#L25-L26).
- Update [example](https://github.com/inveniosoftware/datacite/blob/master/tests/example/full.py)
- Update documentation and add a section about testing with the DataCite API (should mainly link to DataCite documentation.
