### ISSUE TITLE
Support new datacite testing api

### ISSUE THREAD

**Issue by hannu40k** [inveniosoftware/datacite#47]
Hello,

Are there any plans to support the new DOI test environment, as outlined here https://blog.datacite.org/test-prefix-10-5072-retiring-june-1/ ?

Br, Hannu

**Comment by lnielsen** [comment]
You should be able to use the new test environment already. The ``url`` parameter to ``DataCiteMDSClient`` should do the job:

```python
from datacite import DataCiteMDSClient

d = DataCiteMDSClient(
    username='MYDC.MYACCOUNT',
    password='mypassword',
    prefix='10.1234',
    url='https://mds.test.datacite.org',
)```

**Comment by lnielsen** [comment]
Same as #46
