### ISSUE TITLE
Read The Docs not updating

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/datacite#65]
Package version (if known): 1.1.1

## Describe the bug
While the documentation in Sphinx is building correctly, the Read The Docs (https://datacite.readthedocs.io/en/latest/) version is not updating.

## Steps to Reproduce
1. Go to https://datacite.readthedocs.io/en/latest/
2. See that v1.0.1 is the last version

## Expected behavior
Updated docs are available

## Additional context
I can't get access to Read the Docs to check the configuration. Switching to GitHub Actions and Pages is a possible alternative that I could help with.

**Comment by tmorrell** [comment]
I have changed the docs link to https://datacite-test.readthedocs.io/, which I set up under my personal account. It's working correctly without any changes to the repo, so I can't really debug this issue without access to the readthedocs account. A PR is open for changing the link in the readme #71 

Once we figure out who has access to the readthedocs account, the documentation link in both places should be changed back to  https://datacite.readthedocs.io

**Comment by lnielsen** [comment]
I've given you access to the readthedocs now. Ping me on Discord if for some reason it doesn't work.

**Comment by tmorrell** [comment]
Thanks @lnielsen! It was a python2 vs python3 issue in readthedocs.
