### ISSUE TITLE
Support for DataCite schema 4.4

### ISSUE THREAD

**Issue by mhl10** [inveniosoftware/datacite#69]
Dear Invenio team (and welcome @mfenner to InvenioRDM!):

First, thanks for making this tool publicly available. I was wondering if you had any plans in the near future to add support for the DataCite schema 4.4? We (arXiv) are planning on registering DOIs with DataCite within the next few months and some of the changes from 4.4 would be useful (like the `preprint` value in the `resourceTypeGeneral` property). 

In case there are no immediate plans for an update, I'll likely fork and raise a PR at some point.

Cheers,
Martin Lessmeister
arXiv

**Comment by tmorrell** [comment]
We're going to skip 4.4 and go right to 4.5 https://github.com/inveniosoftware/datacite/issues/81, unless someone has a particular need for 4.4 support.
