### ISSUE TITLE
schema41 nameType is not accepting Organizational

### ISSUE THREAD

**Issue by DamienAlbert** [inveniosoftware/datacite#79]
Package version (if known): 1.1.3

## Describe the bug
When validating the JSON metadata for a DOI with `schema41`, its is deemed invalid by the plugin if you have a nameType 'Organizational'. 

## Steps to Reproduce
1. Use `schema41.validate` on a metadata (or `schema41.validator.validate` to be able to log the exceptions)
2. Have a metadata entry containing 'Organizational' with a 'z'
3. Catch the error to display the log : `jsonschema.exceptions.ValidationError (ERROR): 'Organizational' is not one of ['Organisational', 'Personal']`

## Expected behavior

'Organizational' is an accepted value for the DataCite nameType schema, cf. view-source:https://schema.datacite.org/meta/kernel-4.1/include/datacite-nameType-v4.1.xsd

## Additional context

The issue is not present in schema 4.2 and later versions.

**Comment by tmorrell** [comment]
Unless someone particularly needs 4.1 and want to make a PR, using 4.2 or later seems like a acceptable solution.
