### ISSUE TITLE
Add functions for generating Datacite metadata XML

### ISSUE THREAD

**Issue by sloria** [inveniosoftware/datacite#8]
Are there plans to add any helpers for building the [Datacite-formatted metadata XML](http://schema.datacite.org/meta/kernel-3/index.html)? 

We've had to use our own lxml-based helper [here](https://github.com/CenterForOpenScience/osf.io/blob/580edee149a83bf6e8962b893ad5fc9961888be6/website/identifiers/metadata.py#L18-39), which works but is not complete to spec. It would be useful to have support in this package or as a separate package.

**Comment by lnielsen** [comment]
We use an XSL transformation ourselves which is also not the nicest, but it's not high priority to have it fixed so currently there's no plan. We'll however be happy to accept pull requests :-) If it's something you'd like to contribute with, I'd be happy to discuss further.

We are working on inveniosoftware/jsonalchemy which will store data according to JSON Schema defined data model + a second library to do transformations (e.g. data model JSON to a DataCite JSON that can be serialised to XML).

**Comment by lnielsen** [comment]
FYI, this has been implemented now in #10
