### ISSUE TITLE
Discrepancies between JSON schema and DataCite REST API (identifiers and doi)

### ISSUE THREAD

**Issue by edager** [inveniosoftware/datacite#80]
Package version (if known): 1.1.3

## Describe the bug

The field `"dentifiers"` corresponds to the optional field additionalIdentifiers in the DataCite XSD, however, in the json schema v4.3 `"dentifiers"` is a required field, which is not correct (see https://github.com/datacite/schema/issues/134).

Furthermore, the `"doi"` field is pseudo required in the sense that if not provided in a POST request it will be generated automatically  (in the XSD `"doi"` is the `"identifier"` element and it is required). It might make sense to have `"doi"` optional, at least from the perspective of validation (if it needs to correspond not only with the REST API but with the XSD it should be a required field) ?           

## Additional context

If help is wanted for updating the v4.3, or creating v4.5 I would be willing to help out.

**Comment by tmorrell** [comment]
This is fixed in the 4.5 schema. I'd lean toward leaving the 4.3 schema as-is unless there is a compelling need to fix it.
